version: "2"
services:
  app:
    container_name: nginx_lua
    build:
      context: ./openresty
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./code:/nginx/html
      - ./site_lua.conf:/nginx/conf/nginx.conf
      - ./my.conf:/etc/mysql/percona-server.conf.d/mysqld.cnf
    depends_on:
      - "db"
      - "phpmyadmin"


  db:
    image: percona:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
       - ./my.conf:/etc/mysql/percona-server.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql_pma
    ports:
      - "8080:80"


